using System;

namespace Platform.Runtime.Domain;

/// <summary>
/// Base class for all entities generated by the platform.
/// Includes standard audit fields.
/// </summary>
public abstract class Entity
{
    public Guid Id { get; set; }
    
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public string? CreatedBy { get; set; }
    
    public DateTime? ModifiedAt { get; set; }
    public string? ModifiedBy { get; set; }
}
