FROM python:3.10-slim

WORKDIR /app

RUN pip install poetry

COPY pyproject.toml .

# Install dependencies
RUN poetry config virtualenvs.create false \
    && poetry install --no-interaction --no-ansi --no-root

COPY . .

EXPOSE 5018

CMD ["poetry", "run", "python", "app/main.py"]
